"""Initial migration.

Revision ID: 45126565542c
Revises: 
Create Date: 2023-09-06 14:55:15.273914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45126565542c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
